# worker/wrangler.toml
name = "everinvests-worker"
main = "src/index.ts"
compatibility_date = "2026-01-14"

[triggers]
crons = ["0 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "everinvests-db"
database_id = "92386766-33b5-4dc8-a594-abf6fc4e6600"

[ai]
binding = "AI"
